### PR TITLE
Edited switch_settings.conf in switch-kde

### PR DESCRIPTION
**Pull request by juniperdev**
**NOTE: Release was not edited in this pull request. I was not sure of what script you used to generate your Release files and I did not want to tamper with the repo any further. Please update the Release files before merging :)**

Added two lines to the configuration file:
+ [General]
+ InputMethod=qtvirtualkeyboard

This makes it so that the button to display the virtual keyboard is always present at the login screen, preventing a softlock if the user does not have access to a physical keyboard.

Edited the Packages file for dists/l4t/noble/binary-arm64 to account for the changes made above
Added Packages.gz

### CODE REVIEW

**Comment by theofficialgman** [comment]
Hi I'm closing this because this repo is for debs only. The sources that make these debs are in a separate repo.
Also, their shouldn't be a way to have a softlock on the login screen as the button always appears on the login screen as is to popup a keyboard. If you have a use case on a fresh install that can cause the button to not be present please describe a sequence of steps to get that to occur starting with the fresh image.

**Comment by juniperdev** [comment]
Sorry about that! (I haven't had much experience with repositories and only experience with fixing broken packages rather than editing the source files, so I apologize for not making this pull request at the respective repo.) I did some further debugging and the issue I am trying to describe seems to be a monitor/resolution issue with SDDM or KDE rather than a package in this repo. The issue would occur when the console was put to sleep while docked and connected to a TV and then 'woken' out of sleep while in handheld mode. I assume SDDM does not update its display resolution when it is put to sleep at one resolution and woken up in another. I'm not quite sure if that's what happening but that seems to be my understanding. Anyways, the reason for my confusion is that the time, profile picture and password textbox were all visible during this 'big monitor resolution on tiny monitor' moment and it made the virtual keyboard button which is always present at the bottom left (which was still there, just not being displayed) seem like it disappeared. Then, a sort of conformation bias happened where I found an issue that sounded similar online and tried to commit changes to fix that issue here. I apologize for any confusion or hassle this may have caused. Thank you for your speedy response.

**Comment by theofficialgman** [comment]
Thanks for the reproduction steps. Your assumption about SDDM is probably correct. I'm unable to experiment at this time and quite busy recently but if you want you can attempt to ssh into the console from another device when the login screen looks to be the wrong size. There may be commands you can execute (to xorg or SDDM) that will fix/update the resolution. If you did a command or command sequence that works around the issue let me know.

**Comment by juniperdev** [comment]
Hi, I did some further debugging and found out that when this issue occurs, xrandr detects both the internal display (the switch's display) and the external display (whatever was connected through the dock) as 'connected'. Here's the xrandr output on my switch when the issue occurs:


Screen 0: minimum 8 x 8, current 1280 x 720, maximum 16384 x 16384
DSI-0 connected 1280x720+0+0 left (normal left inverted right x axis y axis) 0mm x 0mm
   720x1280      60.00*+
DP-0 connected (normal left inverted right x axis y axis)
   1920x1080     60.00 +  59.95    30.00    29.97    24.00    23.98  
   1600x1200     60.01  
   1360x768      60.02  
   1280x1024     75.03    60.00  
   1280x768      59.87  
   1280x720      60.00    59.94  
   1024x768      75.03    70.07    60.01  
   800x600       75.00    72.19    60.32    56.25  
   720x480       59.94  
   720x400       70.04  
   640x480       75.00    72.81    59.94

As a result, SDDM seems to render onto the only actual display connected (the internal display) with the previous active display's settings and resolution. A workaround for this is to set the mode of the previously active display (in this case, DP-0) to a matching resolution of the internal display (DSI-0), in this case 1280x720 correlates to 720x1280. Here's the xrandr command for the workaround: `xrandr --output DP-0 --mode 1280x720` (`xrandr -display :0.0 --output DP-0 --mode 1280x720` if issuing the command over ssh)

This lets you see the virtual keyboard at the bottom and actually log in to KDE. You would then need to reconfigure your external display settings back to what you had them set as.

For some reason, in this state, I was unable to disable or turn off the phantom external display; xrandr would simply not do it.

**Comment by theofficialgman** [comment]
Huh that is strange. Just to confirm, you ran the xrandr command when not docked, right?

**Comment by juniperdev** [comment]
Correct, it was ran in handheld mode over SSH

**Pull request closed without merging**
